monax/bosmarmot

monax/keys/keys.go, monax/pkgs/jobs/jobs_contracts.go, monax/pkgs/jobs/jobs_transact.go
These fixes address issues of undefined references to NewBurrowKeyClient in three files; PR in reference to Issue #2
=> Fixing undefined references to NewBurrowKeyClient

Makefile, compilers/tests/compilers_test.go, keys/monax-keys/app.go, monax/cmd/monax.go, monax/definitions/do.go, monax/tests/test_jobs.sh, scripts/deps/README.md, scripts/deps/solc.sh, scripts/go_build_revision.sh
- Make bin-wrapper work for compiler and epm test
- Source solidity 0.4.4
- Print versions for files
See also https://github.com/monax/bosmarmot/commit/9c03bc270d58410423e72bda51db396537fa6db4 pushed to master in order to get this on track where I also upgraded all dependencies (including Burrow)
=> Improve test and dependency handling

monax/tests/test_jobs.sh, scripts/deps/burrow.sh
=> Update Burrow version to one that exits on SIGTERM

Makefile, monax/tests/burrow.toml, test/chain/burrow.toml, test/run_js_tests.sh
And provide some test jobs needed by Burrow
=> Use fully formed listen address for rpc

README.md
=> update readme with instructions

Gopkg.lock, scripts/deps/solc.sh, vendor/github.com/hyperledger/burrow/execution/evm/asm/opcodes.go, vendor/github.com/hyperledger/burrow/execution/evm/vm.go, vendor/github.com/hyperledger/burrow/execution/execution.go, vendor/github.com/hyperledger/burrow/execution/transactor.go
builds on #33 now that RETURNDATASIZE has been merged into burrow
=> solc upgrade fix

tests/scripts/deps/solc.sh
=> Use solc from gcloud rather than google drive

tests/run_pkgs_tests.sh
=> Remove .burrow in test runner

README.md
=> Update bos command line in readme

bos/abi/abi.go
=> Fix unpacking bytesN as string and there is no string

Makefile
=> Add in no burrow js tests and fix makefile target renames

bos/compile/compilers_test.go, bos/compile/perform_compilation.go
=> Generate devdoc

vent/README.md, vent/cmd/vent.go, vent/config/config.go, vent/service/consumer.go, vent/service/consumer_test.go, vent/sqldb/adapters/README.md, vent/sqldb/adapters/postgres_adapter.go, vent/sqldb/db_adapter.go, vent/sqldb/sqldb.go, vent/sqldb/sqldb_test.go, vent/sqldb/utils.go, vent/sqlsol/parser.go, vent/sqlsol/parser_test.go, vent/test/db.go, vent/types/sql_column_type.go, vent/types/sql_error_type.go, vent/types/sql_table.go
postgres v9 and above supported out of the box
generic logic isolated from adapter implementation
=> Refactor vent component to be able to add new sql adapters

README.md, burrow.js/README.md, burrow.js/lib/contracts/function.js, burrow.js/package-lock.json, burrow.js/package.json, example/basic-app/.gitignore, example/basic-app/README.md, example/basic-app/app.js, example/basic-app/deploy.yaml, example/basic-app/makefile, example/basic-app/package-lock.json, example/basic-app/package.json, example/basic-app/simplestorage.sol
This will run burrow and use burrow.js to interact with a contract.
=> Add a basic example app with end-to-end example makefile

burrow.js/README.md
Payload should be the Object of the Form 
Changes: Making Input field an Object.
=> Update GRPC Access Component Example

vent/service/consumer.go
=> Using streaming request to get events

vent/cmd/vent.go, vent/service/consumer.go, vent/service/consumer_test.go
=> Fix integration test

.circleci/config.yml, vent/Dockerfile
Provides a Dockerfile to build a vent image and appends a new job for CI to automatically publish to quay.
=> Vent Docker Build

.circleci/config.yml
Signed-off-by: greg <greg.hill@monax.io>
=> fix ci formatting

.circleci/config.yml
Signed-off-by: greg <greg.hill@monax.io>
=> use burrow ci cont

vent/Dockerfile
Signed-off-by: greg <greg.hill@monax.io>
=> docker entrypoint

vent/cmd/vent.go, vent/service/consumer.go, vent/service/consumer_test.go, vent/service/server_test.go
Signed-off-by: Casey Kuhlman <casey@monax.io>
=> leverage external events channel

Gopkg.toml
=> Remove transitive deps

vent/cmd/vent.go
Signed-off-by: Casey Kuhlman <casey@monax.io>
=> fix vent loading disigenuity

vent/cmd/vent.go, vent/service/consumer.go, vent/sqldb/adapters/postgres_adapter.go
Signed-off-by: Casey Kuhlman <casey@monax.io>
=> vent specs loader fix

vent/service/consumer.go, vent/service/decoder.go, vent/service/rowbuilder.go, vent/service/server.go, vent/sqldb/adapters/postgres_adapter.go, vent/sqldb/adapters/sqlite_adapter.go, vent/sqldb/sqldb.go, vent/sqldb/utils.go, vent/sqlsol/spec_loader.go, vent/test/db.go, vent/types/sql_table.go
log level changed to `info` mostly, so calling vent with `--log-level="info"` gets rid of waiting for... & other similar messages.
=> consumer decomposing & log level changes

burrow.js/README.md
Signed-off-by: miguelmartinezinf <miguelmartinezariasinf@gmail.com>
Adds descriptive docs and fixes some typos
Adds final example
=> docs: burrow.js readme enhance

burrow.js/README.md, example/basic-app/README.md, example/basic-app/app.js, example/basic-app/makefile, example/basic-app/package-lock.json, example/basic-app/package.json, example/basic-app/simplestorage.sol
=> Add send/create contract JS example

vent/service/consumer.go
=> Log height

.circleci/Dockerfile, burrow.js/lib/contracts/event.js, burrow.js/lib/contracts/function.js, burrow.js/lib/utils/convert.js, burrow.js/lib/utils/utils.js, burrow.js/package-lock.json, burrow.js/package.json, package-lock.json
Merging from feature branch to fix tests, see: https://github.com/monax/bosmarmot/pull/187
=> Replace Web3 with ethjs-abi

example/basic-app-website/simplestorage.sol, example/basic-app/simplestorage.sol
=> Fixup contracts for solidity 0.5

burrow.js/protobuf/acm.proto, burrow.js/protobuf/balance.proto, burrow.js/protobuf/crypto.proto, burrow.js/protobuf/dump.proto, burrow.js/protobuf/exec.proto, burrow.js/protobuf/github.com/gogo/protobuf/gogoproto/gogo.proto, burrow.js/protobuf/github.com/tendermint/tendermint/abci/types/types.proto, burrow.js/protobuf/github.com/tendermint/tendermint/libs/common/types.proto, burrow.js/protobuf/google/protobuf/descriptor.proto, burrow.js/protobuf/google/protobuf/timestamp.proto, burrow.js/protobuf/keys.proto, burrow.js/protobuf/payload.proto, burrow.js/protobuf/permission.proto, burrow.js/protobuf/rpc.proto, burrow.js/protobuf/rpcdump.proto, burrow.js/protobuf/rpcevents.proto, burrow.js/protobuf/rpcquery.proto, burrow.js/protobuf/rpctransact.proto, burrow.js/protobuf/spec.proto, burrow.js/protobuf/tendermint.proto, burrow.js/protobuf/validator.proto
=> Update protobuf from burrow develop
